Document: syslinux
Title: Debian syslinux Manual
Author: <insert document author here>
Abstract: This manual describes what syslinux is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/syslinux/syslinux.sgml.gz

Format: postscript
Files: /usr/share/doc/syslinux/syslinux.ps.gz

Format: text
Files: /usr/share/doc/syslinux/syslinux.text.gz

Format: HTML
Index: /usr/share/doc/syslinux/html/index.html
Files: /usr/share/doc/syslinux/html/*.html
