Summary: grub2 resources generated by grub2-mknetdir
Name: grub2-xcat
# This el10 rewrite reset the version scheme from the el7-era 2.02 down to 1.0, but
# xCAT-server still Requires: grub2-xcat >= 2.02-0.76.el7.1.snap201905160255. An Epoch
# bump makes 1:1.0 outrank 0:2.02 so the (unchanged) xCAT-server dependency resolves.
Epoch: 1
Version: 1.0
#Release: snap%(date +"%Y%m%d%H%M")
Release: 3
License: GPLv3+
Group: Applications/System
Vendor: IBM Corp.
Packager: IBM Corp.
#Distribution: %{?_distribution:%{_distribution}}%{!?_distribution:%{_vendor}}
Prefix: /tftpboot/boot/grub2
BuildRoot: /var/tmp/%{name}-root
BuildArch: noarch
Source1: grub2-res.tar.gz
# EL10 riscv64 grub2 UEFI image, taken unmodified from the Rocky Linux 10
# BaseOS riscv64 tree (EFI/BOOT/grubriscv64.efi, built from
# grub2-2.12-46.el10_2.rocky.0.1.src.rpm, GPL-3.0-or-later); see readme.
Source2: grubriscv64.efi

Provides: grub2-xcat 
Requires:/bin/sh


%description
grub2-xcat provides some grub2 resources generated by grub2-mknetdir,including grub2 modules and grub2 image,
and the EL grub2 UEFI image for riscv64 nodes, which boot through UEFI and grub2 only.

%define _binaries_in_noarch_packages_terminate_build   0

%prep
#cp ./grub2-res.tar.gz /root/rpmbuild/SOURCES/
#%ifos linux
#tar zxf %{SOURCE1}
#%else
#rm -rf tftpboot
#cp %{SOURCE1} /opt/freeware/src/packages/BUILD
#gunzip -f grub2-res.tar.gz
#tar -xf grub2-res.tar
#%endif

%build

%pre


%install
mkdir -p $RPM_BUILD_ROOT/%{prefix}/
cd $RPM_BUILD_ROOT/%{prefix}/

%ifos linux
tar zxf %{SOURCE1}
%else
cp %{SOURCE1} $RPM_BUILD_ROOT/%{prefix}/
gunzip -f grub2-res.tar.gz
tar -xf grub2-res.tar
%endif
mkdir -p $RPM_BUILD_ROOT/%{prefix}/riscv64-efi
install -m 0644 %{SOURCE2} $RPM_BUILD_ROOT/%{prefix}/riscv64-efi/grubriscv64.efi



%post
rm -f %{prefix}/grub2.ppc
cp  %{prefix}/powerpc-ieee1275/core.elf %{prefix}/grub2.ppc
# riscv64 firmware loads boot/grub2/grub2.riscv64 (DHCP client architecture 27)
rm -f %{prefix}/grub2.riscv64
cp  %{prefix}/riscv64-efi/grubriscv64.efi %{prefix}/grub2.riscv64
exit 0

%clean


%files
#%{prefix}
# one for sles, one for rhel. yes, it's ugly...
%{prefix}/powerpc-ieee1275/
%{prefix}/riscv64-efi/
%defattr(-,root,root)

%postun

if [ "$1" = "0"  ]; then
   rm %{prefix}/grub2.ppc
   rm -f %{prefix}/grub2.riscv64
fi
true
